"""
Created by: John Morales
Class: GUI Development
Assignment: Assignment P2

Python Version: 3.12
"""
#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 26, 2024 08:29:54 PM EST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import payroll_calculator_gui

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = payroll_calculator_gui.Toplevel1(_top1)
    root.mainloop()

if __name__ == '__main__':
    payroll_calculator_gui.start_up()




