#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Mar 05, 2024 05:35:49 PM EST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 600x700+912+314
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4100 1133
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Comic Convention Registration"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 20 -weight bold" \
        -foreground #e4562a -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Group Size:" 
    vTcl:DefineAlias "$top.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #6bcdea \
        -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 20 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Calculate" 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 20 -weight bold" \
        -foreground #e4562a -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Registration Cost:" 
    vTcl:DefineAlias "$top.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -compound left -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 28 -weight bold" \
        -foreground #e4562a -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Comic Convention Registration" 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$top.lab47" \
        -font "-family {Comic Sans MS} -size 16 -weight bold" \
        -foreground #e4562a -text "Select Badge Type:" -background #6bcdea \
        -height 186 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -width 480 
    vTcl:DefineAlias "$top.lab47" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab47
    radiobutton "$site_3_0.rad49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #6bcdea -compound left -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 16 -weight bold" \
        -foreground #e4562a -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -justify left -text "Convention" \
        -variable "selectedBadge" 
    vTcl:DefineAlias "$site_3_0.rad49" "Radiobutton3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton "$site_3_0.rad48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #6bcdea -compound left -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 16 -weight bold" \
        -foreground #e4562a -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -justify left -text "Convention + Autographs" \
        -variable "selectedBadge" 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton "$site_3_0.rad47" \
        -activebackground #6bcdea -activeforeground black -anchor w \
        -background #6bcdea -compound left -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 16 -weight bold" \
        -foreground #e4562a -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -justify left \
        -text "Convention + Superhero Experience" -variable "selectedBadge" 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.rad49 \
        -in $site_3_0 -x 0 -relx 0.083 -y 0 -rely 0.683 -width 0 \
        -relwidth 0.875 -height 0 -relheight 0.242 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.083 -y 0 -rely 0.43 -width 0 \
        -relwidth 0.875 -height 0 -relheight 0.242 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad47 \
        -in $site_3_0 -x 0 -relx 0.083 -y 0 -rely 0.177 -width 0 \
        -relwidth 0.875 -height 0 -relheight 0.243 -anchor nw \
        -bordermode ignore 
    button "$top.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #6bcdea \
        -command "def bClear():
    pass" -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 20 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -relief ridge -text "Clear" 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "Toplevel1" 1
    frame "$top.fra47" \
        -borderwidth 2 -background #d9d9d9 -height 215 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 605 
    vTcl:DefineAlias "$top.fra47" "HeaderFrame" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.fra47
    entry "$top.ent50" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 18 -weight bold" \
        -foreground #e4562a -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black \
        -textvariable "GroupSizeInput" -width 84 
    vTcl:DefineAlias "$top.ent50" "EntryGroupSize" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Comic Sans MS} -size 20 -weight bold" \
        -foreground #e4562a -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -textvariable "CostOutput" 
    vTcl:DefineAlias "$top.lab52" "LblCost" vTcl:WidgetProc "Toplevel1" 1
    set CostOutput {}
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab49 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.371 -width 0 -relwidth 0.285 \
        -height 0 -relheight 0.116 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.914 -width 167 -relwidth 0 \
        -height 46 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.8 -width 0 -relwidth 0.457 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -y 0 -rely 0.286 -width 0 -relwidth 1.007 -height 0 \
        -relheight 0.117 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.5 -width 0 -relwidth 0.8 \
        -height 0 -relheight 0.266 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.583 -y 0 -rely 0.914 -width 167 -relwidth 0 \
        -height 46 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.008 -height 0 \
        -relheight 0.294 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.4 -width 84 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.583 -y 0 -rely 0.8 -width 0 -relwidth 0.323 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

