#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 11, 2024 03:51:51 PM EST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
from PIL import ImageTk, Image

_location = os.path.dirname(__file__)

import burger_specials_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40'
_image_folder = "images/"


#Constants
_instructions = '''Choose a burger and then click the Select Meal button'''
_confirmation = '''Enjoy your burger special'''


class frmBurgers:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("800x590+1304+354")
        top.minsize(120, 1)
        top.maxsize(3632, 3581)
        top.resizable(1,  1)
        top.title("Burger Specials")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.picVeggie = tk.Label(self.top)
        self.picVeggie.place(relx=0.55, rely=0.102, relheight=0.424
                             , relwidth=0.325)
        self.picVeggie.configure(background="#d9d9d9")
        self.picVeggie.configure(borderwidth="2")
        self.picVeggie.configure(highlightbackground="#d9d9d9")
        self.picVeggie.configure(highlightcolor="#000000")
        self.picVeggie.configure(relief="ridge")

        self.lblHeading = tk.Label(self.top)
        self.lblHeading.place(relx=0.275, rely=0.017, height=33, width=352)
        self.lblHeading.configure(activebackground="#d9d9d9")
        self.lblHeading.configure(activeforeground="black")
        self.lblHeading.configure(background="#d9d9d9")
        self.lblHeading.configure(compound='left')
        self.lblHeading.configure(disabledforeground="#a3a3a3")
        self.lblHeading.configure(font="-family {Tahoma} -size 16 -weight bold")
        self.lblHeading.configure(foreground="#000000")
        self.lblHeading.configure(highlightbackground="#d9d9d9")
        self.lblHeading.configure(highlightcolor="#000000")
        self.lblHeading.configure(text='''Farm Burger Specials''')

        #Canvas Ref: https://tkdocs.com/tutorial/canvas.html
        self.picPrime = tk.Label(self.top)
        self.picPrime.place(relx=0.1, rely=0.102, relheight=0.424
                , relwidth=0.325)
        self.picPrime.configure(background="#d9d9d9")
        self.picPrime.configure(borderwidth="2")
        self.picPrime.configure(highlightbackground="#d9d9d9")
        self.picPrime.configure(highlightcolor="#000000")
        self.picPrime.configure(relief="ridge")

        self.btnVeggie = tk.Button(self.top)
        self.btnVeggie.place(relx=0.663, rely=0.576, height=35, width=128)
        self.btnVeggie.configure(activebackground="#d9d9d9")
        self.btnVeggie.configure(activeforeground="black")
        self.btnVeggie.configure(background="#d9d9d9")
        self.btnVeggie.configure(disabledforeground="#a3a3a3")
        self.btnVeggie.configure(font="-family {Segoe UI} -size 9")
        self.btnVeggie.configure(foreground="#000000")
        self.btnVeggie.configure(highlightbackground="#d9d9d9")
        self.btnVeggie.configure(highlightcolor="#000000")
        self.btnVeggie.configure(text='''Veggie''')
        self.btnVeggie.configure(command=self.veggie_button_click)

        self.btnExit = tk.Button(self.top)
        self.btnExit.place(relx=0.425, rely=0.898, height=35, width=128)
        self.btnExit.configure(activebackground="#d9d9d9")
        self.btnExit.configure(activeforeground="black")
        self.btnExit.configure(background="#d9d9d9")
        self.btnExit.configure(disabledforeground="#a3a3a3")
        self.btnExit.configure(font="-family {Segoe UI} -size 9")
        self.btnExit.configure(foreground="#000000")
        self.btnExit.configure(highlightbackground="#d9d9d9")
        self.btnExit.configure(highlightcolor="#000000")
        self.btnExit.configure(text='''Exit Window''')
        self.btnExit.configure(command=quit)

        self.btnSelectMeal = tk.Button(self.top)
        self.btnSelectMeal.place(relx=0.42, rely=0.576, height=35, width=128)
        self.btnSelectMeal.configure(activebackground="#d9d9d9")
        self.btnSelectMeal.configure(activeforeground="black")
        self.btnSelectMeal.configure(background="#d9d9d9")
        self.btnSelectMeal.configure(disabledforeground="#a3a3a3")
        self.btnSelectMeal.configure(font="-family {Segoe UI} -size 9")
        self.btnSelectMeal.configure(foreground="#000000")
        self.btnSelectMeal.configure(highlightbackground="#d9d9d9")
        self.btnSelectMeal.configure(highlightcolor="#000000")
        self.btnSelectMeal.configure(text='''Select Meal''')
        self.btnSelectMeal.configure(state=DISABLED)

        self.lblInstructions = tk.Label(self.top)
        self.lblInstructions.place(relx=0.275, rely=0.673, height=19, width=360)
        self.lblInstructions.configure(activebackground="#d9d9d9")
        self.lblInstructions.configure(activeforeground="black")
        self.lblInstructions.configure(background="#d9d9d9")
        self.lblInstructions.configure(disabledforeground="#a3a3a3")
        self.lblInstructions.configure(font="-family {Tahoma} -size 9")
        self.lblInstructions.configure(foreground="#000000")
        self.lblInstructions.configure(highlightbackground="#d9d9d9")
        self.lblInstructions.configure(highlightcolor="#000000")
        self.lblInstructions.configure(text=_instructions)

        self.btnPrime = tk.Button(self.top)
        self.btnPrime.place(relx=0.163, rely=0.576, height=35, width=128)
        self.btnPrime.configure(activebackground="#d9d9d9")
        self.btnPrime.configure(activeforeground="black")
        self.btnPrime.configure(background="#d9d9d9")
        self.btnPrime.configure(disabledforeground="#a3a3a3")
        self.btnPrime.configure(font="-family {Segoe UI} -size 9")
        self.btnPrime.configure(foreground="#000000")
        self.btnPrime.configure(highlightbackground="#d9d9d9")
        self.btnPrime.configure(highlightcolor="#000000")
        self.btnPrime.configure(text='''Prime Beef''')
        self.btnPrime.configure(command=self.prime_beef_button_click)

        self.lblConfirmation = tk.Label(self.top)
        self.lblConfirmation.place(relx=0.393, rely=0.714, height=19, width=172)
        self.lblConfirmation.configure(activebackground="#d9d9d9")
        self.lblConfirmation.configure(activeforeground="black")
        self.lblConfirmation.configure(background="#d9d9d9")
        self.lblConfirmation.configure(compound='left')
        self.lblConfirmation.configure(disabledforeground="#a3a3a3")
        self.lblConfirmation.configure(font="-family {Tahoma} -size 9")
        self.lblConfirmation.configure(foreground="#000000")
        self.lblConfirmation.configure(highlightbackground="#d9d9d9")
        self.lblConfirmation.configure(highlightcolor="#000000")
        self.lblConfirmation.configure(text=None)

    def prime_beef_button_click(self):
        _prime_image = Image.open(_image_folder + "prime.jpg")
        _prime_photo = ImageTk.PhotoImage(_prime_image.resize((260, 250)))

        self.picPrime.configure(image=_prime_photo)
        self.picPrime.image = _prime_photo
        self.picPrime.place(anchor='center',x=125, y=125)
        self.picVeggie.image = None

    def veggie_button_click(self):
        _veggie_image = Image.open(_image_folder + "veggie.jpg")
        _veggie_photo = ImageTk.PhotoImage(_veggie_image.resize((260,250)))

        self.picVeggie.configure(image=_veggie_photo)
        self.picVeggie.image = _veggie_photo
        self.picVeggie.place(anchor='center', x=125, y=125)
        self.picPrime.image = None


def start_up():
    burger_specials_support.main()

if __name__ == '__main__':
    burger_specials_support.main()




