#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Apr 29, 2024 09:50:43 PM EDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m57 -background #b0c4de -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 800x800+1279+226
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2052 1261
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Building Plans Conversion"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "frmBuildingPlansConversion" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f2f2 \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 15 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "Clear List" 
    vTcl:DefineAlias "$top.but49" "btnClearList" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    button "$top.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f2f2 \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 15 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "Save to File" 
    vTcl:DefineAlias "$top.but50" "btnSaveToFile" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    button "$top.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f2f2 \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 15 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "Clear Results" 
    vTcl:DefineAlias "$top.but51" "btnClearResults" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    button "$top.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f2f2 \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 15 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "Save Results" 
    vTcl:DefineAlias "$top.but48" "btnSaveResults" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    button "$top.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f2f2 \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 15 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "Convert" 
    vTcl:DefineAlias "$top.but47" "btnConvert" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    menu "$top.m57" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    frame "$top.fra51" \
        -borderwidth 2 -background #b0c4de -height 205 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 805 
    vTcl:DefineAlias "$top.fra51" "HeaderFrame" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    set site_3_0 $top.fra51
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #b0c4de -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 24 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Converter App 2" 
    vTcl:DefineAlias "$site_3_0.lab53" "lblTitle" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    label "$site_3_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor nw \
        -background #b0c4de -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 16 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Enter a value and choose conversion" 
    vTcl:DefineAlias "$site_3_0.lab54" "lblInstructions" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    entry "$site_3_0.ent47" \
        -background #0000ff -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 16 -weight bold" \
        -foreground #ffffff -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black \
        -textvariable "ValueInput" -width 134 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry1" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    label "$site_3_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "building.jpg" 
    vTcl:DefineAlias "$site_3_0.lab52" "lblPic" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.388 -y 0 -rely 0.036 -width 0 \
        -relwidth 0.53 -height 0 -relheight 0.299 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.391 -width 0 \
        -relwidth 0.295 -height 0 -relheight 0.297 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 0 -relx 0.775 -y 0 -rely 0.471 -width 134 \
        -relwidth 0 -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -width 0 -relwidth 0.33 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    labelframe "$top.lab48" \
        -font "-family {Segoe UI} -size 18 -weight bold" -foreground #ffffff \
        -text "Convert Measurement" -background #0000ff -height 130 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 452 
    vTcl:DefineAlias "$top.lab48" "lblFrameSelection" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    set site_3_0 $top.lab48
    radiobutton "$site_3_0.rad48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #0000ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18" -foreground #ffffff \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Meters to Inches" -variable "selectedButton" 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton2" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    radiobutton "$site_3_0.rad47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #0000ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18" -foreground #ffffff \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Inches to Meters" -variable "selectedButton" 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton1" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.044 -y 0 -rely 0.692 -width 0 \
        -relwidth 0.759 -height 0 -relheight 0.154 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad47 \
        -in $site_3_0 -x 0 -relx 0.044 -y 0 -rely 0.308 -width 0 \
        -relwidth 0.759 -height 0 -relheight 0.215 -anchor nw \
        -bordermode ignore 
    listbox "$top.lis56" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 14" -foreground #000000 \
        -height 332 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 264 \
        -listvariable "lstResults" 
    $top.lis56 configure -font "-family {Courier New} -size 14"
    $top.lis56 insert end text
    vTcl:DefineAlias "$top.lis56" "lstBoxResults" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #b0c4de -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 16 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "10 meters oi 234.333 inches" -textvariable "txtConversion" 
    vTcl:DefineAlias "$top.lab47" "lblOutput" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    set txtConversion {10 meters oi 234.333 inches}
    label "$top.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #b0c4de -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 16 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "10 meters oi 234.333 inches" -textvariable "txtFileSave" 
    vTcl:DefineAlias "$top.lab55" "lblOutput_1" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    set txtFileSave {10 meters oi 234.333 inches}
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but49 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.825 -width 127 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.825 -width 127 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.725 -width 177 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.638 -width 177 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.475 -width 177 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra51 \
        -in $top -x 0 -relx -0.013 -y 0 -rely 0.013 -width 0 -relwidth 1 \
        -height 0 -relheight 0.344 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.388 -y 0 -rely 0.288 -width 0 -relwidth 0.565 \
        -height 0 -relheight 0.165 -anchor nw -bordermode ignore 
    place $top.lis56 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.375 -width 0 -relwidth 0.33 \
        -height 0 -relheight 0.415 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.388 -y 0 -rely 0.525 -width 0 -relwidth 0.569 \
        -height 0 -relheight 0.105 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.788 -width 0 -relwidth 0.57 \
        -height 0 -relheight 0.105 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

