#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Mar 09, 2024 01:38:19 PM EST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #c0c0ff -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 800x600+556+321
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2052 1261
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Building Plans Conversion"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "frmBuildingPlansConversion" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #c0c0ff \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "Exit" 
    vTcl:DefineAlias "$top.but50" "btnExit" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #c0c0ff \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "Clear" 
    vTcl:DefineAlias "$top.but49" "btnClear" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    button "$top.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #c0c0ff \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -relief ridge \
        -text "Convert" 
    vTcl:DefineAlias "$top.but47" "btnConvert" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor e \
        -background #c0c0ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 20 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "10 meters oi 234.333 inches" 
    vTcl:DefineAlias "$top.lab47" "lblOutput" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    frame "$top.fra51" \
        -borderwidth 2 -background #c0c0ff -height 205 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 805 
    vTcl:DefineAlias "$top.fra51" "HeaderFrame" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    set site_3_0 $top.fra51
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #c0c0ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 24 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Converter App" 
    vTcl:DefineAlias "$site_3_0.lab53" "lblTitle" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    entry "$site_3_0.ent47" \
        -background #4b0083 -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 20 -weight bold" \
        -foreground #ffffff -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black \
        -textvariable "ValueInput" -width 134 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry1" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    label "$site_3_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "building.jpg" 
    vTcl:DefineAlias "$site_3_0.lab52" "lblPic" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    label "$site_3_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor nw \
        -background #c0c0ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 20 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Enter a value and choose conversion" 
    vTcl:DefineAlias "$site_3_0.lab54" "lblInstructions" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.375 -y 0 -rely 0.049 -width 0 \
        -relwidth 0.53 -height 0 -relheight 0.298 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 0 -relx 0.775 -y 0 -rely 0.537 -width 134 \
        -relwidth 0 -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.33 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.39 -width 0 -relwidth 0.295 \
        -height 0 -relheight 0.444 -anchor nw -bordermode ignore 
    labelframe "$top.lab48" \
        -font "-family {Segoe UI} -size 18 -weight bold" -foreground #ffffff \
        -text "Convert Measurement" -background #4b0083 -height 165 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 340 
    vTcl:DefineAlias "$top.lab48" "lblFrameSelection" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    set site_3_0 $top.lab48
    radiobutton "$site_3_0.rad47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #4b0083 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18" -foreground #ffffff \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Inches to Meters" -variable "selectedButton" 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton1" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    radiobutton "$site_3_0.rad48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #4b0083 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18" -foreground #ffffff \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Meters to Inches" -variable "selectedButton" 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton2" vTcl:WidgetProc "frmBuildingPlansConversion" 1
    place $site_3_0.rad47 \
        -in $site_3_0 -x 0 -relx 0.029 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.759 -height 0 -relheight 0.212 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.029 -y 0 -rely 0.606 -width 0 \
        -relwidth 0.759 -height 0 -relheight 0.152 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but50 \
        -in $top -x 0 -relx 0.694 -y 0 -rely 0.817 -width 177 -relwidth 0 \
        -height 56 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.39 -y 0 -rely 0.817 -width 177 -relwidth 0 \
        -height 56 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.817 -width 177 -relwidth 0 \
        -height 56 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.683 -width 0 -relwidth 0.593 \
        -height 0 -relheight 0.102 -anchor nw -bordermode ignore 
    place $top.fra51 \
        -in $top -x 0 -y 0 -rely 0.05 -width 0 -relwidth 1 -height 0 \
        -relheight 0.342 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.525 -y 0 -rely 0.4 -width 0 -relwidth 0.425 \
        -height 0 -relheight 0.275 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

