#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Feb 26, 2024 08:29:42 PM EST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 800x575+861+312
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2756 2033
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Payroll Every Two Weeks"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra48" \
        -borderwidth 2 -background #d9d9d9 -height 325 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 805 
    vTcl:DefineAlias "$top.fra48" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    button "$site_3_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #0290fe \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #ffffff \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Clear" 
    vTcl:DefineAlias "$site_3_0.but48" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "State Tax:" 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Federal Tax:" 
    vTcl:DefineAlias "$site_3_0.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #0290fe \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #ffffff \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Compute Taxes" 
    vTcl:DefineAlias "$site_3_0.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 14 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Net Paycheck Income:" 
    vTcl:DefineAlias "$site_3_0.lab53" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "FICA:" 
    vTcl:DefineAlias "$site_3_0.lab50" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Label" \
        -textvariable "lblFICAOut" 
    vTcl:DefineAlias "$site_3_0.lab55" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Label" \
        -textvariable "lblFederalTaxOut" 
    vTcl:DefineAlias "$site_3_0.lab56" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 14 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Label" \
        -textvariable "lblNetIncomeOut" 
    vTcl:DefineAlias "$site_3_0.lab54" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 20 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Enter Gross Pay:" 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #0290fe \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #ffffff \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Exit" 
    vTcl:DefineAlias "$site_3_0.but49" "Button3" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Label" \
        -textvariable "lblStateTaxOut" 
    vTcl:DefineAlias "$site_3_0.lab57" "Label9" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent49" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Arial} -size 14" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "GrossPayInput" -width 174 
    vTcl:DefineAlias "$site_3_0.ent49" "EntryGrossPay" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.447 -y 0 -rely 0.338 -width 130 \
        -relwidth 0 -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.671 -y 0 -rely 0.585 -width 0 \
        -relwidth 0.117 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.385 -y 0 -rely 0.585 -width 0 \
        -relwidth 0.117 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.186 -y 0 -rely 0.338 -width 130 \
        -relwidth 0 -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.211 -y 0 -rely 0.738 -width 0 \
        -relwidth 0.291 -height 0 -relheight 0.126 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.199 -y 0 -rely 0.585 -width 0 \
        -relwidth 0.056 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.286 -y 0 -rely 0.585 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.534 -y 0 -rely 0.585 -width 0 \
        -relwidth 0.104 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.547 -y 0 -rely 0.738 -width 0 \
        -relwidth 0.216 -height 0 -relheight 0.126 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.236 -y 0 -rely 0.123 -width 0 \
        -relwidth 0.288 -height 0 -relheight 0.126 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.683 -y 0 -rely 0.338 -width 130 \
        -relwidth 0 -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.795 -y 0 -rely 0.585 -width 0 \
        -relwidth 0.117 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 0 -relx 0.534 -y 0 -rely 0.123 -width 174 \
        -relwidth 0 -height 40 -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.fra47" \
        -borderwidth 2 -background #d9d9d9 -height 275 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 805 
    vTcl:DefineAlias "$top.fra47" "HeaderFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    canvas "$site_3_0.can48" \
        -background #d9d9d9 -borderwidth 2 -closeenough 1.0 -height 293 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 412 
    vTcl:DefineAlias "$site_3_0.can48" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -compound left -disabledforeground #a3a3a3 \
        -font "-family {Cooper Black} -size 24 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Payroll Calculator" 
    vTcl:DefineAlias "$site_3_0.lab49" "ProgramTitle" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -compound left -disabledforeground #a3a3a3 \
        -font "-family {Cooper Black} -size 18 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Paycheck Calculation" 
    vTcl:DefineAlias "$site_3_0.lab47" "ProgramDescription" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.can48 \
        -in $site_3_0 -x 0 -relx -0.012 -y 0 -rely -0.036 -width 0 \
        -relwidth 0.512 -height 0 -relheight 1.065 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.509 -y 0 -rely 0.109 -width 0 \
        -relwidth 0.489 -height 0 -relheight 0.185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.509 -y 0 -rely 0.4 -width 0 \
        -relwidth 0.488 -height 0 -relheight 0.222 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra48 \
        -in $top -x 0 -y 0 -rely 0.452 -width 0 -relwidth 1.006 -height 0 \
        -relheight 0.565 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -y 0 -rely -0.017 -width 0 -relwidth 1.006 -height 0 \
        -relheight 0.478 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

