#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Apr 29, 2024 08:24:19 PM EDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import building_plans_conversion_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class frmBuildingPlansConversion:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("800x800+1279+226")
        top.minsize(120, 1)
        top.maxsize(2052, 1261)
        top.resizable(1,  1)
        top.title("Building Plans Conversion")
        top.configure(background="#b0c4de")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.ValueInput = tk.StringVar()
        self.txtConversion = tk.StringVar()
        self.txtFileSave = tk.StringVar()
        self.selectedButton = tk.IntVar()
        self.lstResults = tk.StringVar()

        self.btnClearList = tk.Button(self.top)
        self.btnClearList.place(relx=0.025, rely=0.825, height=36, width=127)
        self.btnClearList.configure(activebackground="#d9d9d9")
        self.btnClearList.configure(activeforeground="black")
        self.btnClearList.configure(background="#f2f2f2")
        self.btnClearList.configure(disabledforeground="#a3a3a3")
        self.btnClearList.configure(font="-family {Segoe UI} -size 15 -weight bold")
        self.btnClearList.configure(foreground="#000000")
        self.btnClearList.configure(highlightbackground="#d9d9d9")
        self.btnClearList.configure(highlightcolor="#000000")
        self.btnClearList.configure(relief="ridge")
        self.btnClearList.configure(text='''Clear List''')

        self.btnSaveToFile = tk.Button(self.top)
        self.btnSaveToFile.place(relx=0.2, rely=0.825, height=36, width=127)
        self.btnSaveToFile.configure(activebackground="#d9d9d9")
        self.btnSaveToFile.configure(activeforeground="black")
        self.btnSaveToFile.configure(background="#f2f2f2")
        self.btnSaveToFile.configure(disabledforeground="#a3a3a3")
        self.btnSaveToFile.configure(font="-family {Segoe UI} -size 15 -weight bold")
        self.btnSaveToFile.configure(foreground="#000000")
        self.btnSaveToFile.configure(highlightbackground="#d9d9d9")
        self.btnSaveToFile.configure(highlightcolor="#000000")
        self.btnSaveToFile.configure(relief="ridge")
        self.btnSaveToFile.configure(text='''Save to File''')

        self.btnClearResults = tk.Button(self.top)
        self.btnClearResults.place(relx=0.4, rely=0.725, height=36, width=177)
        self.btnClearResults.configure(activebackground="#d9d9d9")
        self.btnClearResults.configure(activeforeground="black")
        self.btnClearResults.configure(background="#f2f2f2")
        self.btnClearResults.configure(disabledforeground="#a3a3a3")
        self.btnClearResults.configure(font="-family {Segoe UI} -size 15 -weight bold")
        self.btnClearResults.configure(foreground="#000000")
        self.btnClearResults.configure(highlightbackground="#d9d9d9")
        self.btnClearResults.configure(highlightcolor="#000000")
        self.btnClearResults.configure(relief="ridge")
        self.btnClearResults.configure(text='''Clear Results''')

        self.btnSaveResults = tk.Button(self.top)
        self.btnSaveResults.place(relx=0.4, rely=0.638, height=36, width=177)
        self.btnSaveResults.configure(activebackground="#d9d9d9")
        self.btnSaveResults.configure(activeforeground="black")
        self.btnSaveResults.configure(background="#f2f2f2")
        self.btnSaveResults.configure(disabledforeground="#a3a3a3")
        self.btnSaveResults.configure(font="-family {Segoe UI} -size 15 -weight bold")
        self.btnSaveResults.configure(foreground="#000000")
        self.btnSaveResults.configure(highlightbackground="#d9d9d9")
        self.btnSaveResults.configure(highlightcolor="#000000")
        self.btnSaveResults.configure(relief="ridge")
        self.btnSaveResults.configure(text='''Save Results''')

        self.btnConvert = tk.Button(self.top)
        self.btnConvert.place(relx=0.4, rely=0.475, height=36, width=177)
        self.btnConvert.configure(activebackground="#d9d9d9")
        self.btnConvert.configure(activeforeground="black")
        self.btnConvert.configure(background="#f2f2f2")
        self.btnConvert.configure(disabledforeground="#a3a3a3")
        self.btnConvert.configure(font="-family {Segoe UI} -size 15 -weight bold")
        self.btnConvert.configure(foreground="#000000")
        self.btnConvert.configure(highlightbackground="#d9d9d9")
        self.btnConvert.configure(highlightcolor="#000000")
        self.btnConvert.configure(relief="ridge")
        self.btnConvert.configure(text='''Convert''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.HeaderFrame = tk.Frame(self.top)
        self.HeaderFrame.place(relx=-0.013, rely=0.013, relheight=0.345
                , relwidth=1.0)
        self.HeaderFrame.configure(relief='flat')
        self.HeaderFrame.configure(borderwidth="2")
        self.HeaderFrame.configure(background="#b0c4de")
        self.HeaderFrame.configure(highlightbackground="#d9d9d9")
        self.HeaderFrame.configure(highlightcolor="#000000")

        self.lblPic = tk.Label(self.HeaderFrame)
        self.lblPic.place(relx=0.038, rely=0.0, height=276, width=264)
        self.lblPic.configure(activebackground="#d9d9d9")
        self.lblPic.configure(activeforeground="black")
        self.lblPic.configure(background="#d9d9d9")
        self.lblPic.configure(compound='left')
        self.lblPic.configure(disabledforeground="#a3a3a3")
        self.lblPic.configure(font="-family {Segoe UI} -size 9")
        self.lblPic.configure(foreground="#000000")
        self.lblPic.configure(highlightbackground="#d9d9d9")
        self.lblPic.configure(highlightcolor="#000000")
        self.lblPic.configure(text='''building.jpg''')

        self.lblTitle = tk.Label(self.HeaderFrame)
        self.lblTitle.place(relx=0.388, rely=0.036, height=82, width=424)
        self.lblTitle.configure(activebackground="#d9d9d9")
        self.lblTitle.configure(activeforeground="black")
        self.lblTitle.configure(anchor='w')
        self.lblTitle.configure(background="#b0c4de")
        self.lblTitle.configure(compound='left')
        self.lblTitle.configure(disabledforeground="#a3a3a3")
        self.lblTitle.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.lblTitle.configure(foreground="#000000")
        self.lblTitle.configure(highlightbackground="#d9d9d9")
        self.lblTitle.configure(highlightcolor="#000000")
        self.lblTitle.configure(text='''Converter App 2''')

        self.lblInstructions = tk.Label(self.HeaderFrame)
        self.lblInstructions.place(relx=0.4, rely=0.391, height=82, width=236)
        self.lblInstructions.configure(activebackground="#d9d9d9")
        self.lblInstructions.configure(activeforeground="black")
        self.lblInstructions.configure(anchor='nw')
        self.lblInstructions.configure(background="#b0c4de")
        self.lblInstructions.configure(compound='left')
        self.lblInstructions.configure(disabledforeground="#a3a3a3")
        self.lblInstructions.configure(font="-family {Segoe UI} -size 16 -weight bold")
        self.lblInstructions.configure(foreground="#000000")
        self.lblInstructions.configure(highlightbackground="#d9d9d9")
        self.lblInstructions.configure(highlightcolor="#000000")
        self.lblInstructions.configure(text='''Enter a value and choose conversion''')

        self.Entry1 = tk.Entry(self.HeaderFrame)
        self.Entry1.place(relx=0.775, rely=0.471, height=50, relwidth=0.168)
        self.Entry1.configure(background="#0000ff")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Courier New} -size 16 -weight bold")
        self.Entry1.configure(foreground="#ffffff")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="#000000")
        self.Entry1.configure(insertbackground="#000000")
        self.Entry1.configure(selectbackground="#d9d9d9")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=self.ValueInput)

        self.lblFrameSelection = tk.LabelFrame(self.top)
        self.lblFrameSelection.place(relx=0.388, rely=0.288, relheight=0.165
                , relwidth=0.565)
        self.lblFrameSelection.configure(relief='groove')
        self.lblFrameSelection.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.lblFrameSelection.configure(foreground="#ffffff")
        self.lblFrameSelection.configure(text='''Convert Measurement''')
        self.lblFrameSelection.configure(background="#0000ff")
        self.lblFrameSelection.configure(highlightbackground="#d9d9d9")
        self.lblFrameSelection.configure(highlightcolor="#000000")

        self.Radiobutton2 = tk.Radiobutton(self.lblFrameSelection)
        self.Radiobutton2.place(relx=0.044, rely=0.689, relheight=0.159
                , relwidth=0.759, bordermode='ignore')
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="black")
        self.Radiobutton2.configure(anchor='w')
        self.Radiobutton2.configure(background="#0000ff")
        self.Radiobutton2.configure(compound='left')
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(font="-family {Segoe UI} -size 18")
        self.Radiobutton2.configure(foreground="#ffffff")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="#000000")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''Meters to Inches''')
        self.Radiobutton2.configure(variable=self.selectedButton)

        self.Radiobutton1 = tk.Radiobutton(self.lblFrameSelection)
        self.Radiobutton1.place(relx=0.044, rely=0.311, relheight=0.212
                , relwidth=0.759, bordermode='ignore')
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(activeforeground="black")
        self.Radiobutton1.configure(anchor='w')
        self.Radiobutton1.configure(background="#0000ff")
        self.Radiobutton1.configure(compound='left')
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(font="-family {Segoe UI} -size 18")
        self.Radiobutton1.configure(foreground="#ffffff")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="#000000")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''Inches to Meters''')
        self.Radiobutton1.configure(variable=self.selectedButton)

        self.lstBoxResults = tk.Listbox(self.top)
        self.lstBoxResults.place(relx=0.025, rely=0.375, relheight=0.415
                , relwidth=0.33)
        self.lstBoxResults.configure(background="white")
        self.lstBoxResults.configure(disabledforeground="#a3a3a3")
        self.lstBoxResults.configure(font="-family {Courier New} -size 14")
        self.lstBoxResults.configure(foreground="#000000")
        self.lstBoxResults.configure(highlightbackground="#d9d9d9")
        self.lstBoxResults.configure(highlightcolor="#000000")
        self.lstBoxResults.configure(selectbackground="#d9d9d9")
        self.lstBoxResults.configure(selectforeground="black")
        self.lstBoxResults.configure(listvariable=self.lstResults)

        self.lblOutput = tk.Label(self.top)
        self.lblOutput.place(relx=0.388, rely=0.525, height=84, width=456)
        self.lblOutput.configure(activebackground="#d9d9d9")
        self.lblOutput.configure(activeforeground="black")
        self.lblOutput.configure(anchor='w')
        self.lblOutput.configure(background="#b0c4de")
        self.lblOutput.configure(compound='left')
        self.lblOutput.configure(disabledforeground="#a3a3a3")
        self.lblOutput.configure(font="-family {Segoe UI} -size 16 -weight bold")
        self.lblOutput.configure(foreground="#000000")
        self.lblOutput.configure(highlightbackground="#d9d9d9")
        self.lblOutput.configure(highlightcolor="#000000")
        self.lblOutput.configure(text='''10 meters oi 234.333 inches''')
        self.lblOutput.configure(textvariable=self.txtConversion)
        self.txtConversion.set('''10 meters oi 234.333 inches''')

        self.lblOutput_1 = tk.Label(self.top)
        self.lblOutput_1.place(relx=0.4, rely=0.788, height=84, width=456)
        self.lblOutput_1.configure(activebackground="#d9d9d9")
        self.lblOutput_1.configure(activeforeground="black")
        self.lblOutput_1.configure(anchor='w')
        self.lblOutput_1.configure(background="#b0c4de")
        self.lblOutput_1.configure(compound='left')
        self.lblOutput_1.configure(disabledforeground="#a3a3a3")
        self.lblOutput_1.configure(font="-family {Segoe UI} -size 16 -weight bold")
        self.lblOutput_1.configure(foreground="#000000")
        self.lblOutput_1.configure(highlightbackground="#d9d9d9")
        self.lblOutput_1.configure(highlightcolor="#000000")
        self.lblOutput_1.configure(text='''10 meters oi 234.333 inches''')
        self.lblOutput_1.configure(textvariable=self.txtFileSave)
        self.txtFileSave.set('''10 meters oi 234.333 inches''')

def start_up():
    building_plans_conversion_support.main()

if __name__ == '__main__':
    building_plans_conversion_support.main()




