#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 05, 2024 05:35:49 PM EST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
from PIL import ImageTk, Image

_location = os.path.dirname(__file__)

import comic_con_registration_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40'
_image_folder = "images/"

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x700+912+314")
        top.minsize(120, 1)
        top.maxsize(4100, 1133)
        top.resizable(1,  1)
        top.title("Comic Convention Registration")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.GroupSizeInput = tk.StringVar()
        self.CostOutput = tk.StringVar()
        self.selectedBadge = tk.IntVar(value=1)

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.25, rely=0.371, height=81, width=171)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Comic Sans MS} -size 20 -weight bold")
        self.Label2.configure(foreground="#e4562a")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''Group Size:''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.15, rely=0.914, height=46, width=167)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#6bcdea")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Comic Sans MS} -size 20 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Calculate''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.133, rely=0.8, height=41, width=274)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Comic Sans MS} -size 20 -weight bold")
        self.Label3.configure(foreground="#e4562a")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="#000000")
        self.Label3.configure(text='''Registration Cost:''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.0, rely=0.286, height=82, width=604)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Comic Sans MS} -size 28 -weight bold")
        self.Label1.configure(foreground="#e4562a")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Comic Convention Registration''')

        self.Labelframe1 = tk.LabelFrame(self.top)
        self.Labelframe1.place(relx=0.1, rely=0.5, relheight=0.266, relwidth=0.8)

        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="-family {Comic Sans MS} -size 16 -weight bold")
        self.Labelframe1.configure(foreground="#e4562a")
        self.Labelframe1.configure(text='''Select Badge Type:''')
        self.Labelframe1.configure(background="#6bcdea")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="#000000")

        self.Radiobutton3 = tk.Radiobutton(self.Labelframe1)
        self.Radiobutton3.place(relx=0.083, rely=0.683, relheight=0.242
                , relwidth=0.875, bordermode='ignore')
        self.Radiobutton3.configure(activebackground="#d9d9d9")
        self.Radiobutton3.configure(activeforeground="black")
        self.Radiobutton3.configure(anchor='w')
        self.Radiobutton3.configure(background="#6bcdea")
        self.Radiobutton3.configure(compound='left')
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(font="-family {Comic Sans MS} -size 16 -weight bold")
        self.Radiobutton3.configure(foreground="#e4562a")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="#000000")
        self.Radiobutton3.configure(justify='left')
        self.Radiobutton3.configure(text='''Convention''')
        self.Radiobutton3.configure(variable=self.selectedBadge)
        self.Radiobutton3.configure(value=3)

        self.Radiobutton2 = tk.Radiobutton(self.Labelframe1)
        self.Radiobutton2.place(relx=0.083, rely=0.43, relheight=0.242
                , relwidth=0.875, bordermode='ignore')
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="black")
        self.Radiobutton2.configure(anchor='w')
        self.Radiobutton2.configure(background="#6bcdea")
        self.Radiobutton2.configure(compound='left')
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(font="-family {Comic Sans MS} -size 16 -weight bold")
        self.Radiobutton2.configure(foreground="#e4562a")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="#000000")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''Convention + Autographs''')
        self.Radiobutton2.configure(variable=self.selectedBadge)
        self.Radiobutton2.configure(value=2)

        self.Radiobutton1 = tk.Radiobutton(self.Labelframe1)
        self.Radiobutton1.place(relx=0.083, rely=0.177, relheight=0.242
                , relwidth=0.875, bordermode='ignore')
        self.Radiobutton1.configure(activebackground="#6bcdea")
        self.Radiobutton1.configure(activeforeground="black")
        self.Radiobutton1.configure(anchor='w')
        self.Radiobutton1.configure(background="#6bcdea")
        self.Radiobutton1.configure(compound='left')
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(font="-family {Comic Sans MS} -size 16 -weight bold")
        self.Radiobutton1.configure(foreground="#e4562a")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="#000000")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''Convention + Superhero Experience''')
        self.Radiobutton1.configure(variable=self.selectedBadge)
        self.Radiobutton1.configure(value=1)

        self.btnClear = tk.Button(self.top)
        self.btnClear.place(relx=0.583, rely=0.914, height=46, width=167)
        self.btnClear.configure(activebackground="#d9d9d9")
        self.btnClear.configure(activeforeground="black")
        self.btnClear.configure(background="#6bcdea")
        self.btnClear.configure(command=self.clear)
        self.btnClear.configure(disabledforeground="#a3a3a3")
        self.btnClear.configure(font="-family {Comic Sans MS} -size 20 -weight bold")
        self.btnClear.configure(foreground="#000000")
        self.btnClear.configure(highlightbackground="#d9d9d9")
        self.btnClear.configure(highlightcolor="#000000")
        self.btnClear.configure(relief="ridge")
        self.btnClear.configure(text='''Clear''')

        self.HeaderFrame = tk.Frame(self.top)
        self.HeaderFrame.place(relx=0.0, rely=0.0, relheight=0.294
                , relwidth=1.008)
        self.HeaderFrame.configure(relief='flat')
        self.HeaderFrame.configure(borderwidth="2")
        self.HeaderFrame.configure(background="#d9d9d9")
        self.HeaderFrame.configure(highlightbackground="#d9d9d9")
        self.HeaderFrame.configure(highlightcolor="#000000")

        self.picComic = tk.Label(self.HeaderFrame)
        self.picComic.place(relx=0, rely=0, relheight=1.0, relwidth=1)
        with Image.open(_image_folder + "comic.jpg") as comic_image:
            HeaderFrame_size = (605, 206)
            photo = ImageTk.PhotoImage(comic_image.resize(HeaderFrame_size))
            self.picComic.configure(image=photo)
            self.picComic.image = photo

        self.EntryGroupSize = tk.Entry(self.top)
        self.EntryGroupSize.place(relx=0.617, rely=0.4, height=50, relwidth=0.14)

        self.EntryGroupSize.configure(background="white")
        self.EntryGroupSize.configure(disabledforeground="#a3a3a3")
        self.EntryGroupSize.configure(font="-family {Comic Sans MS} -size 18 -weight bold")
        self.EntryGroupSize.configure(foreground="#e4562a")
        self.EntryGroupSize.configure(highlightbackground="#d9d9d9")
        self.EntryGroupSize.configure(highlightcolor="#000000")
        self.EntryGroupSize.configure(insertbackground="#000000")
        self.EntryGroupSize.configure(selectbackground="#d9d9d9")
        self.EntryGroupSize.configure(selectforeground="black")
        self.EntryGroupSize.configure(textvariable=self.GroupSizeInput)
        self.EntryGroupSize.focus_set()

        self.LblCost = tk.Label(self.top)
        self.LblCost.place(relx=0.583, rely=0.8, height=41, width=194)
        self.LblCost.configure(activebackground="#d9d9d9")
        self.LblCost.configure(activeforeground="black")
        self.LblCost.configure(anchor='w')
        self.LblCost.configure(background="#d9d9d9")
        self.LblCost.configure(compound='left')
        self.LblCost.configure(disabledforeground="#a3a3a3")
        self.LblCost.configure(font="-family {Comic Sans MS} -size 20 -weight bold")
        self.LblCost.configure(foreground="#e4562a")
        self.LblCost.configure(highlightbackground="#d9d9d9")
        self.LblCost.configure(highlightcolor="#000000")
        self.LblCost.configure(textvariable=self.CostOutput)
        self.CostOutput.set('''''')

    def clear(self):
        #Clears the user input and outputs
        self.selectedBadge.set(1)
        self.CostOutput.set("")
        self.GroupSizeInput.set("")
        self.EntryGroupSize.focus_set()

def start_up():
    comic_con_registration_support.main()

if __name__ == '__main__':
    comic_con_registration_support.main()




